name: ai1
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_2
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.1=py38h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - freetype=2.12.1=ha860e81_0
  - git=2.34.1=haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=py38haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.8=h2bbff1b_5
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.4.0=h8a3f274_2
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - openssl=1.1.1s=h2bbff1b_0
  - pillow=9.2.0=py38hdc2b20a_1
  - pip=20.3.3=py38haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - requests=2.28.1=py38haa95532_0
  - setuptools=65.5.0=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - torchvision=0.12.0=py38_cu113
  - typing_extensions=4.3.0=py38haa95532_0
  - urllib3=1.26.12=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - xz=5.2.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.3.0
    - accelerate==0.14.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - albumentations==0.4.3
    - altair==4.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backports-zoneinfo==0.2.1
    - bidict==0.22.0
    - blinker==1.5
    - cachetools==5.2.0
    - click==8.1.3
    - colorama==0.4.6
    - commonmark==0.9.1
    - decorator==5.1.1
    - diffusers==0.9.0
    - dnspython==2.2.1
    - einops==0.3.0
    - entrypoints==0.4
    - eventlet==0.33.2
    - filelock==3.8.0
    - flask==2.1.2
    - flask-cors==3.0.10
    - flask-socketio==5.2.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - future==0.18.2
    - gevent==22.10.2
    - gevent-websocket==0.10.1
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - greenlet==2.0.1
    - grpcio==1.51.1
    - huggingface-hub==0.11.1
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imgaug==0.2.6
    - importlib-metadata==5.1.0
    - importlib-resources==5.10.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - kornia==0.6.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - multidict==6.0.2
    - networkx==2.8.8
    - numpy==1.23.5
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.5.2
    - pkgutil-resolve-name==1.3.10
    - protobuf==3.20.3
    - psutil==5.9.4
    - pudb==2019.2
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeck==0.8.0
    - pydeprecate==0.3.1
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - python-dotenv==0.21.0
    - python-engineio==4.3.4
    - python-socketio==5.7.2
    - pytorch-lightning==1.4.2
    - pytz==2022.6
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.3
    - semver==2.13.0
    - smmap==5.0.0
    - streamlit==1.15.1
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - test-tube==0.7.5
    - tifffile==2022.10.10
    - tokenizers==0.13.2
    - toml==0.10.2
    - toolz==0.12.0
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - tornado==6.2
    - tqdm==4.64.1
    - transformers==4.24.0
    - tzdata==2022.6
    - tzlocal==4.2
    - urwid==2.1.2
    - validators==0.20.0
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.11.0
    - zope-event==4.5.0
    - zope-interface==5.5.2
